language: php

php:
  - 7.0
  - 7.1

env:
  - TESTBENCH_VERSION=3.4.* ILLUMINATE_VERSION=5.4.* PHPUNIT_VERSION=~5.7 # Laravel 5.4
  - TESTBENCH_VERSION=3.5.* ILLUMINATE_VERSION=5.5.* PHPUNIT_VERSION=~6.0 # Laravel 5.5
  - TESTBENCH_VERSION=3.6.* ILLUMINATE_VERSION=5.6.* PHPUNIT_VERSION=~7.0 # Laravel 5.6

matrix:
  exclude:
  - php: 7.0
    env: TESTBENCH_VERSION=3.6.* ILLUMINATE_VERSION=5.6.* PHPUNIT_VERSION=~7.0

before_install:
  - composer require orchestra/testbench:${TESTBENCH_VERSION} phpunit/phpunit:${PHPUNIT_VERSION}

install: composer install --no-interaction --prefer-dist

script: vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
