language: php

matrix:
  include:
  - php: 7.0
    env: LARAVEL='5.5.*'
  - php: 7.1
    env: LARAVEL='5.5.*'
  - php: 7.1
    env: LARAVEL='5.6.*'
  - php: 7.2
    env: LARAVEL='5.5.*'
  - php: 7.2
    env: LARAVEL='5.6.*'

before_install:
  - composer require illuminate/contracts:${LARAVEL}

install: composer install --no-interaction --prefer-dist

script: vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
